import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Drop Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Drop Notes
        </h1>

        <p className={styles.description}>
          Welcome to Drop Notes . one place for all Notes!
        </p>

        <div className={styles.grid}>
          <Link href="login">
            <a className={styles.card}>
              <h2>Create Courses &rarr;</h2>
              <p>You can create your own Courses for Free.</p>
            </a>
          </Link>


          <a href="" className={styles.card}>
            <h2>Courses &rarr;</h2>
            <p>Best Courses that people had created.</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Video Lectures &rarr;</h2>
            <p>See Best Free video Lectures..</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Notes &rarr;</h2>
            <p>
              Download Free Notes Form Courses.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>

        <p>@2022 DropNotes.com All rights reserved .</p>
      </footer>
    </div>
  )
}
